LINE_CHANNEL_ACCESS_TOKEN: 'PTyEtELM5//vjv3oBBn4Jur12yoHa/ejt4wqvtKyhnm00sqwdMOk/eUNspmNMP/JvX2W+vl3CTHyyP8NKQoZRwJ92+5DxR2rEgzoPbgKb+Su+V2SghVoYj8vgNwC5lwutl7wml5HyPiPVmCJD/hqCo9PbdgDzCFqoOLOYbqAITQ='

expires_in: 2592000

token_type: 'Bearer'

LINE_CHANNEL_SECRET: '8352edca599153f2362bc9b7d3bb2610'


My_Raspberry_PI_IP_ADDRESS: '100.64.1.29'